name: DEMO Workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Run tests
        id: test
        run: |
          if ! go test -v ./...; then
            echo "::set-output name=status::failure"
            exit 1
          else
            echo "::set-output name=status::success"
          fi

  # Add a separate job to handle the failed test case
  handle-failed-test:
    needs: build
    if: ${{ needs.build.outputs.test == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print error message
        run: echo "Tests failed. Please fix the issues and try again."
      # You can add more steps here, such as reverting the commit or preventing the push.
