name: DEMO Workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6" # You can specify any Go version you need

      - name: Run tests
        run: go test -v ./...

      - name: Notify on failure
        if: failure()
        run: echo "Test failed. Please check your code."
