name: DEMO Workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Run tests
        id: test
        run: |
          if ! go test -v ./...; then
            echo "::set-output name=status::failure"
            exit 1
          else
            echo "::set-output name=status::success"
          fi
