name: DEMO Workflows
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Run tests
        run: go test -v ./...

      - name: Check test status
        run: |
          if [ $? -ne 0 ]; then
            echo "::error::Tests failed. Cancelling workflow."
            exit 1
          fi
